[2025-04-30 17:08:05,607: INFO: main: Welcome to info]
[2025-04-30 17:08:17,336: INFO: main: Welcome to info]
[2025-04-30 17:09:08,305: INFO: main: Welcome to info]
[2025-04-30 17:16:14,917: INFO: main: Welcome to info]
[2025-04-30 17:16:42,529: INFO: main: Welcome to info]
[2025-05-05 17:19:02,484: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 17:19:02,491: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 17:19:02,494: INFO: common: created directory at: artifacts]
[2025-05-05 17:19:02,495: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 17:19:02,498: INFO: 986331348: Downloading data from https://drive.google.com/drive/folders/1Os2_hUGKSt97F1KoS5M0ddtsFY1SIao4?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-05 17:19:25,192: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 17:19:25,194: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 17:19:25,196: INFO: common: created directory at: artifacts]
[2025-05-05 17:19:25,198: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 17:19:25,199: INFO: 986331348: Downloading data from https://drive.google.com/drive/folders/1Os2_hUGKSt97F1KoS5M0ddtsFY1SIao4?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-05 17:20:04,225: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 17:20:04,227: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 17:20:04,228: INFO: common: created directory at: artifacts]
[2025-05-05 17:20:04,230: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 17:20:04,232: INFO: 986331348: Downloading data from https://drive.google.com/drive/folders/1Os2_hUGKSt97F1KoS5M0ddtsFY1SIao4?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-05 17:21:37,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 17:21:37,009: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 17:21:37,011: INFO: common: created directory at: artifacts]
[2025-05-05 17:21:37,012: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 17:21:37,014: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-05 17:21:57,615: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-05 17:53:54,866: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-05 17:53:54,869: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 17:53:54,871: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 17:53:54,872: INFO: common: created directory at: artifacts]
[2025-05-05 17:53:54,872: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 17:53:54,873: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-05 17:54:20,185: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-05 17:54:21,206: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 17:14:56,124: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:14:56,144: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:14:56,148: INFO: common: created directory at: artifacts]
[2025-05-06 17:15:41,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:15:41,948: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:15:41,950: INFO: common: created directory at: artifacts]
[2025-05-06 17:19:18,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:19:18,943: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:19:18,945: INFO: common: created directory at: artifacts]
[2025-05-06 17:20:25,321: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:20:25,324: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:20:25,327: INFO: common: created directory at: artifacts]
[2025-05-06 17:22:47,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:22:47,751: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:22:47,754: INFO: common: created directory at: artifacts]
[2025-05-06 17:24:09,167: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:24:09,170: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:24:09,172: INFO: common: created directory at: artifacts]
[2025-05-06 17:25:50,140: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:25:50,144: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:25:50,146: INFO: common: created directory at: artifacts]
[2025-05-06 17:27:13,730: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:27:13,735: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:27:13,737: INFO: common: created directory at: artifacts]
[2025-05-06 17:27:40,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:27:40,662: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:27:40,664: INFO: common: created directory at: artifacts]
[2025-05-06 17:29:23,011: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:29:23,015: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:29:23,018: INFO: common: created directory at: artifacts]
[2025-05-06 17:29:23,021: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-06 17:29:40,194: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 17:29:40,472: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 17:50:54,399: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-06 17:50:54,400: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:50:54,402: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:50:54,402: INFO: common: created directory at: artifacts]
[2025-05-06 17:50:54,404: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-06 17:50:54,404: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-06 17:51:16,509: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-06 17:51:17,262: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-06 17:51:17,263: INFO: main: *******************]
[2025-05-06 17:51:17,263: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-06 17:51:17,264: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:51:17,266: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:51:17,266: INFO: common: created directory at: artifacts]
[2025-05-06 17:51:17,266: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-06 17:51:17,830: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 17:51:18,017: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 17:51:18,213: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-07 17:03:57,360: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-07 17:03:57,378: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:03:57,381: INFO: common: created directory at: artifacts]
[2025-05-07 17:03:57,386: INFO: common: created directory at: artifacts\training]
[2025-05-07 17:03:58,048: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-07 17:05:25,194: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-07 17:23:21,191: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-07 17:23:21,193: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-07 17:23:21,195: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:23:21,195: INFO: common: created directory at: artifacts]
[2025-05-07 17:23:21,195: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-07 17:23:21,196: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-07 17:23:58,409: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-07 17:23:59,126: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-07 17:23:59,126: INFO: main: *******************]
[2025-05-07 17:23:59,127: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-07 17:23:59,128: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-07 17:23:59,130: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:23:59,130: INFO: common: created directory at: artifacts]
[2025-05-07 17:23:59,130: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-07 17:23:59,762: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-07 17:23:59,997: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-07 17:24:00,155: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-07 17:24:00,155: INFO: main: *******************]
[2025-05-07 17:24:00,156: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-07 17:24:00,157: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-07 17:24:00,158: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:24:00,159: INFO: common: created directory at: artifacts]
[2025-05-07 17:24:00,159: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 39, in <module>
    model_trainer.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_training.py", line 21, in main
    training_config = config.get_training_config()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\config\configuration.py", line 59, in get_training_config
    training_data = os.path.join(self.config.data_ingestion.unzip_dir, "kidney-ct-scan-image")
                    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-05-07 17:26:19,892: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-07 17:26:19,895: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-07 17:26:19,896: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:26:19,897: INFO: common: created directory at: artifacts]
[2025-05-07 17:26:19,898: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-07 17:26:19,898: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-07 17:26:41,466: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-07 17:26:42,156: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-07 17:26:42,156: INFO: main: *******************]
[2025-05-07 17:26:42,156: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-07 17:26:42,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-07 17:26:42,160: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:26:42,161: INFO: common: created directory at: artifacts]
[2025-05-07 17:26:42,161: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-07 17:26:42,615: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-07 17:26:42,847: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-07 17:26:43,023: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-07 17:26:43,024: INFO: main: *******************]
[2025-05-07 17:26:43,025: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-07 17:26:43,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-07 17:26:43,029: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-07 17:26:43,030: INFO: common: created directory at: artifacts]
[2025-05-07 17:26:43,037: INFO: common: created directory at: artifacts\training]
[2025-05-07 17:26:43,434: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-07 17:27:51,491: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-07 17:27:51,606: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-08 17:13:00,353: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-08 17:13:00,382: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 17:13:00,395: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 17:13:00,399: INFO: common: created directory at: artifacts]
[2025-05-08 17:13:00,400: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-08 17:13:00,402: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-08 17:14:02,142: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-08 17:14:03,119: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-08 17:14:03,120: INFO: main: *******************]
[2025-05-08 17:14:03,120: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-08 17:14:03,123: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 17:14:03,126: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 17:14:03,128: INFO: common: created directory at: artifacts]
[2025-05-08 17:14:03,129: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-08 17:14:03,748: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-08 17:14:04,037: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-08 17:14:04,374: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-08 17:14:04,375: INFO: main: *******************]
[2025-05-08 17:14:04,376: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-08 17:14:04,378: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 17:14:04,380: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 17:14:04,381: INFO: common: created directory at: artifacts]
[2025-05-08 17:14:04,383: INFO: common: created directory at: artifacts\training]
[2025-05-08 17:14:04,745: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-08 17:15:53,666: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-08 17:15:53,863: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-08 18:16:25,479: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-08 18:16:25,484: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 18:16:25,487: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 18:16:25,490: INFO: common: created directory at: artifacts]
[2025-05-08 18:16:25,490: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-08 18:16:25,491: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-08 18:16:30,836: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion']
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 15, in <module>
    data_ingestion.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\data_ingestion.py", line 23, in main
    data_ingestion.download_file()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\Data_ingestion_01.py", line 33, in download_file
    raise e
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\Data_ingestion_01.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\gdown\download.py", line 304, in download
    for file in os.listdir(osp.dirname(output) or "."):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion'
[2025-05-08 18:17:31,701: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-08 18:17:31,703: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 18:17:31,704: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 18:17:31,705: INFO: common: created directory at: artifacts]
[2025-05-08 18:17:31,705: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-08 18:17:31,706: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-08 18:17:51,108: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-08 18:17:51,676: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-08 18:17:51,676: INFO: main: *******************]
[2025-05-08 18:17:51,677: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-08 18:17:51,678: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 18:17:51,679: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 18:17:51,680: INFO: common: created directory at: artifacts]
[2025-05-08 18:17:51,681: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-08 18:17:52,234: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-08 18:17:52,402: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-08 18:17:52,516: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-08 18:17:52,516: INFO: main: *******************]
[2025-05-08 18:17:52,516: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-08 18:17:52,518: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 18:17:52,519: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 18:17:52,520: INFO: common: created directory at: artifacts]
[2025-05-08 18:17:52,521: INFO: common: created directory at: artifacts\training]
[2025-05-08 18:17:52,770: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-08 18:19:02,965: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-08 18:19:03,074: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-08 18:19:03,075: INFO: main: *******************]
[2025-05-08 18:19:03,075: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-08 18:19:03,076: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-08 18:19:03,078: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-08 18:19:03,078: INFO: common: created directory at: artifacts]
[2025-05-08 18:19:03,293: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-08 18:19:47,317: INFO: common: json file saved at: scores.json]
[2025-05-08 18:19:47,326: INFO: common: json file saved at: scores.json]
[2025-05-08 18:19:48,750: ERROR: main: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 404 != 200. Response body: 'Not Found']
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 51, in <module>
    model_evalution.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 66, in log_into_mlflow
    print("MLflow Experiment:", mlflow.get_experiment_by_name("your_experiment_name"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\fluent.py", line 1548, in get_experiment_by_name
    return MlflowClient().get_experiment_by_name(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 544, in get_experiment_by_name
    return self._tracking_client.get_experiment_by_name(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 236, in get_experiment_by_name
    return self.store.get_experiment_by_name(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 323, in get_experiment_by_name
    response_proto = self._call_endpoint(GetExperimentByName, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 60, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 404 != 200. Response body: 'Not Found'
[2025-05-12 16:26:32,578: INFO: model_eval: *******************]
[2025-05-12 16:26:32,578: INFO: model_eval: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 16:26:32,581: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:26:32,583: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:26:32,587: INFO: common: created directory at: artifacts]
[2025-05-12 16:26:32,592: ERROR: model_eval: [Errno 2] Unable to synchronously open file (unable to open file: name = 'artifacts/training/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)]
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 41, in <module>
    obj.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 23, in main
    evaluation.evaluation()
  File "C:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 47, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 43, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'artifacts/training/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-05-12 16:31:35,589: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 16:31:35,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:31:35,596: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:31:35,596: INFO: common: created directory at: artifacts]
[2025-05-12 16:31:35,598: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 16:31:35,599: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 16:31:59,337: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 16:32:00,811: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 16:32:00,816: INFO: main: *******************]
[2025-05-12 16:32:00,816: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 16:32:00,820: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:32:00,826: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:32:00,832: INFO: common: created directory at: artifacts]
[2025-05-12 16:32:00,841: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 16:32:01,815: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 16:32:02,096: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 16:32:02,329: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 16:32:02,331: INFO: main: *******************]
[2025-05-12 16:32:02,332: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-12 16:32:02,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:32:02,342: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:32:02,343: INFO: common: created directory at: artifacts]
[2025-05-12 16:32:02,345: INFO: common: created directory at: artifacts\training]
[2025-05-12 16:32:02,845: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 16:34:01,848: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 16:34:02,077: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 16:34:02,078: INFO: main: *******************]
[2025-05-12 16:34:02,079: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 16:34:02,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:34:02,087: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:34:02,096: INFO: common: created directory at: artifacts]
[2025-05-12 16:34:02,480: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 16:35:08,531: INFO: common: json file saved at: scores.json]
[2025-05-12 16:35:08,532: INFO: common: json file saved at: scores.json]
[2025-05-12 16:36:05,415: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.']
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 51, in <module>
    model_evalution.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\models\model.py", line 665, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 104, in _register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 2339, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.'
[2025-05-12 16:45:48,625: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 16:45:48,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:45:48,629: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:45:48,630: INFO: common: created directory at: artifacts]
[2025-05-12 16:45:48,631: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 16:45:48,632: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 16:46:20,627: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 16:46:21,628: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 16:46:21,629: INFO: main: *******************]
[2025-05-12 16:46:21,629: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 16:46:21,631: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:46:21,633: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:46:21,634: INFO: common: created directory at: artifacts]
[2025-05-12 16:46:21,634: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 16:46:22,282: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 16:46:22,576: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 16:46:22,781: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 16:46:22,781: INFO: main: *******************]
[2025-05-12 16:46:22,782: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-12 16:46:22,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:46:22,787: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:46:22,788: INFO: common: created directory at: artifacts]
[2025-05-12 16:46:22,790: INFO: common: created directory at: artifacts\training]
[2025-05-12 16:46:23,144: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 16:48:42,992: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 16:48:43,151: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 16:48:43,151: INFO: main: *******************]
[2025-05-12 16:48:43,151: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 16:48:43,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 16:48:43,156: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 16:48:43,157: INFO: common: created directory at: artifacts]
[2025-05-12 16:48:43,418: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 16:49:46,017: INFO: common: json file saved at: scores.json]
[2025-05-12 16:49:46,018: INFO: common: json file saved at: scores.json]
[2025-05-12 16:50:53,410: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.']
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 51, in <module>
    model_evalution.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\models\model.py", line 665, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 104, in _register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 2339, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.'
[2025-05-12 17:00:55,778: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 17:00:55,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:00:55,782: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:00:55,783: INFO: common: created directory at: artifacts]
[2025-05-12 17:00:55,784: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 17:00:55,784: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:01:29,340: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:01:30,417: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 17:01:30,417: INFO: main: *******************]
[2025-05-12 17:01:30,418: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 17:01:30,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:01:30,423: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:01:30,424: INFO: common: created directory at: artifacts]
[2025-05-12 17:01:30,425: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 17:01:31,075: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:01:31,321: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:01:31,528: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 17:01:31,528: INFO: main: *******************]
[2025-05-12 17:01:31,530: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-12 17:01:31,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:01:31,537: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:01:31,541: INFO: common: created directory at: artifacts]
[2025-05-12 17:01:31,543: INFO: common: created directory at: artifacts\training]
[2025-05-12 17:01:31,936: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:03:24,723: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:03:25,052: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 17:03:25,058: INFO: main: *******************]
[2025-05-12 17:03:25,066: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 17:03:25,074: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:03:25,085: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:03:25,099: INFO: common: created directory at: artifacts]
[2025-05-12 17:03:25,681: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:04:28,533: INFO: common: json file saved at: scores.json]
[2025-05-12 17:04:28,534: INFO: common: json file saved at: scores.json]
[2025-05-12 17:05:45,274: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.']
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 51, in <module>
    model_evalution.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\models\model.py", line 665, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 104, in _register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 2339, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.'
[2025-05-12 17:05:59,918: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 17:05:59,920: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:05:59,922: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:05:59,923: INFO: common: created directory at: artifacts]
[2025-05-12 17:05:59,923: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 17:05:59,924: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:06:37,720: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:06:38,606: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 17:06:38,606: INFO: main: *******************]
[2025-05-12 17:06:38,607: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 17:06:38,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:06:38,612: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:06:38,612: INFO: common: created directory at: artifacts]
[2025-05-12 17:06:38,614: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 17:06:39,200: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:06:39,424: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:06:39,581: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 17:06:39,582: INFO: main: *******************]
[2025-05-12 17:06:39,582: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-12 17:06:39,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:06:39,585: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:06:39,586: INFO: common: created directory at: artifacts]
[2025-05-12 17:06:39,587: INFO: common: created directory at: artifacts\training]
[2025-05-12 17:06:39,889: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:08:39,447: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:08:39,773: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 17:08:39,774: INFO: main: *******************]
[2025-05-12 17:08:39,775: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 17:08:39,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:08:39,795: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:08:39,799: INFO: common: created directory at: artifacts]
[2025-05-12 17:08:40,462: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:10:27,379: INFO: common: json file saved at: scores.json]
[2025-05-12 17:10:27,383: INFO: common: json file saved at: scores.json]
[2025-05-12 17:11:32,277: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.']
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 51, in <module>
    model_evalution.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\models\model.py", line 665, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 104, in _register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 2339, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.'
[2025-05-12 17:13:15,143: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 17:13:15,147: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:13:15,150: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:13:15,151: INFO: common: created directory at: artifacts]
[2025-05-12 17:13:15,152: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 17:13:15,153: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:13:42,761: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:13:44,224: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 17:13:44,234: INFO: main: *******************]
[2025-05-12 17:13:44,243: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 17:13:44,266: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:13:44,280: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:13:44,282: INFO: common: created directory at: artifacts]
[2025-05-12 17:13:44,283: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 17:13:44,919: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:13:45,144: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:13:45,306: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 17:13:45,307: INFO: main: *******************]
[2025-05-12 17:13:45,307: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-12 17:13:45,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:13:45,311: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:13:45,311: INFO: common: created directory at: artifacts]
[2025-05-12 17:13:45,312: INFO: common: created directory at: artifacts\training]
[2025-05-12 17:13:45,668: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:16:04,182: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:16:04,411: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 17:16:04,412: INFO: main: *******************]
[2025-05-12 17:16:04,413: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 17:16:04,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:16:04,422: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:16:04,428: INFO: common: created directory at: artifacts]
[2025-05-12 17:16:04,842: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:17:02,694: INFO: common: json file saved at: scores.json]
[2025-05-12 17:17:02,700: INFO: common: json file saved at: scores.json]
[2025-05-12 17:18:39,537: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.']
Traceback (most recent call last):
  File "c:\MyDLProject\Kidney_DL_Project\main.py", line 51, in <module>
    model_evalution.main()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "c:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\models\model.py", line 665, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 104, in _register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 2339, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.'
[2025-05-12 17:35:28,325: INFO: data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 17:35:28,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:35:28,329: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:35:28,330: INFO: common: created directory at: artifacts]
[2025-05-12 17:35:28,330: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 17:35:28,331: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:35:57,277: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:35:58,192: INFO: data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 17:38:46,910: INFO: data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 17:38:46,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:38:46,913: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:38:46,913: INFO: common: created directory at: artifacts]
[2025-05-12 17:38:46,913: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 17:38:46,915: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:39:15,461: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 17:39:16,297: INFO: data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 17:39:34,587: INFO: prepare_base_model: *******************]
[2025-05-12 17:39:34,588: INFO: prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 17:39:34,589: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:39:34,591: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:39:34,591: INFO: common: created directory at: artifacts]
[2025-05-12 17:39:34,592: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 17:39:35,339: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:39:35,692: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:39:35,884: INFO: prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 17:40:59,898: INFO: prepare_base_model: *******************]
[2025-05-12 17:40:59,898: INFO: prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 17:40:59,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:40:59,902: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:40:59,902: INFO: common: created directory at: artifacts]
[2025-05-12 17:40:59,903: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 17:41:00,503: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:41:00,773: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:41:00,967: INFO: prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 17:41:11,591: INFO: model_training: *******************]
[2025-05-12 17:41:11,591: INFO: model_training: >>>>>> stage Training started <<<<<<]
[2025-05-12 17:41:11,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:41:11,595: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:41:11,595: INFO: common: created directory at: artifacts]
[2025-05-12 17:41:11,595: INFO: common: created directory at: artifacts\training]
[2025-05-12 17:41:12,066: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:42:21,988: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:42:22,137: INFO: model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 17:43:03,620: INFO: model_training: *******************]
[2025-05-12 17:43:03,621: INFO: model_training: >>>>>> stage Training started <<<<<<]
[2025-05-12 17:43:03,622: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:43:03,624: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:43:03,624: INFO: common: created directory at: artifacts]
[2025-05-12 17:43:03,625: INFO: common: created directory at: artifacts\training]
[2025-05-12 17:43:03,920: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:44:21,777: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 17:44:21,936: INFO: model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 17:44:34,202: INFO: model_eval: *******************]
[2025-05-12 17:44:34,202: INFO: model_eval: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 17:44:34,205: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 17:44:34,207: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 17:44:34,207: INFO: common: created directory at: artifacts]
[2025-05-12 17:44:34,506: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 17:45:19,851: INFO: common: json file saved at: scores.json]
[2025-05-12 17:45:19,852: INFO: common: json file saved at: scores.json]
[2025-05-12 17:46:03,851: ERROR: model_eval: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.']
Traceback (most recent call last):
  File "C:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 41, in <module>
    obj.main()
  File "C:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "C:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\components\model_eval_04.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\models\model.py", line 665, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 104, in _register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 2339, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.'
[2025-05-12 18:06:07,646: INFO: data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-12 18:06:07,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 18:06:07,651: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 18:06:07,655: INFO: common: created directory at: artifacts]
[2025-05-12 18:06:07,655: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-12 18:06:07,656: INFO: Data_ingestion_01: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 18:06:38,136: INFO: Data_ingestion_01: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-05-12 18:06:39,358: INFO: data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-12 18:06:58,222: INFO: prepare_base_model: *******************]
[2025-05-12 18:06:58,222: INFO: prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 18:06:58,224: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 18:06:58,226: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 18:06:58,227: INFO: common: created directory at: artifacts]
[2025-05-12 18:06:58,227: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 18:06:59,244: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 18:06:59,581: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 18:06:59,838: INFO: prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 18:14:40,527: INFO: prepare_base_model: *******************]
[2025-05-12 18:14:40,528: INFO: prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 18:14:40,536: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 18:14:40,542: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 18:14:40,544: INFO: common: created directory at: artifacts]
[2025-05-12 18:14:40,545: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 18:14:42,062: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 18:14:42,595: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 18:14:42,889: INFO: prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 18:16:03,896: INFO: prepare_base_model: *******************]
[2025-05-12 18:16:03,897: INFO: prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-12 18:16:03,906: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 18:16:03,913: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 18:16:03,915: INFO: common: created directory at: artifacts]
[2025-05-12 18:16:03,917: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-12 18:16:05,426: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 18:16:05,832: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 18:16:06,140: INFO: prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-12 18:16:30,806: INFO: model_training: *******************]
[2025-05-12 18:16:30,807: INFO: model_training: >>>>>> stage Training started <<<<<<]
[2025-05-12 18:16:30,812: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 18:16:30,819: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 18:16:30,821: INFO: common: created directory at: artifacts]
[2025-05-12 18:16:30,823: INFO: common: created directory at: artifacts\training]
[2025-05-12 18:16:31,881: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-12 18:20:13,683: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-12 18:20:14,175: INFO: model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-12 18:20:40,399: INFO: model_eval: *******************]
[2025-05-12 18:20:40,401: INFO: model_eval: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-12 18:20:40,412: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-12 18:20:40,419: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-12 18:20:40,421: INFO: common: created directory at: artifacts]
[2025-05-12 18:20:41,443: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-13 16:40:48,733: INFO: model_eval: *******************]
[2025-05-13 16:40:48,735: INFO: model_eval: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-13 16:40:48,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-13 16:40:48,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-13 16:40:48,749: INFO: common: created directory at: artifacts]
[2025-05-13 16:40:49,782: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-13 16:42:36,892: INFO: common: json file saved at: scores.json]
[2025-05-13 16:42:36,896: INFO: common: json file saved at: scores.json]
[2025-05-13 16:45:00,969: ERROR: model_eval: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.']
Traceback (most recent call last):
  File "C:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 41, in <module>
    obj.main()
  File "C:\MyDLProject\Kidney_DL_Project\src\cnnClassifier\pipeline\model_eval.py", line 31, in main
    evaluation.log_into_mlflow()
  File "c:\mydlproject\kidney_dl_project\src\cnnClassifier\components\model_eval_04.py", line 80, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
           ^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\models\model.py", line 665, in log
    mlflow.tracking._model_registry.fluent._register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 104, in _register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 92, in _register_model
    create_model_response = client.create_registered_model(name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\client.py", line 2339, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\rest_store.py", line 82, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 44, in _call_endpoint
    return call_endpoint(
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 290, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\kidney\Lib\site-packages\mlflow\utils\rest_utils.py", line 179, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: 'Cookies must be enabled to use GitHub.'
[2025-05-13 16:48:22,683: INFO: model_eval: *******************]
[2025-05-13 16:48:22,685: INFO: model_eval: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-13 16:48:22,696: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-13 16:48:22,702: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-13 16:48:22,705: INFO: common: created directory at: artifacts]
[2025-05-13 16:48:23,907: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-13 16:50:48,167: INFO: common: json file saved at: scores.json]
[2025-05-13 16:50:48,169: INFO: common: json file saved at: scores.json]
[2025-05-13 16:50:48,170: INFO: model_eval: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-05-13 17:16:16,810: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.249.86:8080]
[2025-05-13 17:16:16,812: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-13 17:16:16,818: INFO: _internal:  * Restarting with stat]
[2025-05-13 17:16:23,529: WARNING: _internal:  * Debugger is active!]
[2025-05-13 17:16:23,532: INFO: _internal:  * Debugger PIN: 532-605-900]
[2025-05-13 17:17:59,112: INFO: _internal: 127.0.0.1 - - [13/May/2025 17:17:59] "GET / HTTP/1.1" 200 -]
[2025-05-13 17:23:45,794: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-13 17:23:46,788: INFO: _internal: 127.0.0.1 - - [13/May/2025 17:23:46] "POST /predict HTTP/1.1" 200 -]
[2025-05-13 17:24:33,888: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-13 17:24:34,559: INFO: _internal: 127.0.0.1 - - [13/May/2025 17:24:34] "POST /predict HTTP/1.1" 200 -]
[2025-05-13 17:24:55,704: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-13 17:24:56,336: INFO: _internal: 127.0.0.1 - - [13/May/2025 17:24:56] "POST /predict HTTP/1.1" 200 -]
[2025-05-13 17:25:00,964: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-13 17:25:01,779: INFO: _internal: 127.0.0.1 - - [13/May/2025 17:25:01] "POST /predict HTTP/1.1" 200 -]
[2025-05-13 17:52:40,280: INFO: _internal:  * Detected change in 'c:\\MyDLProject\\Kidney_DL_Project\\src\\cnnClassifier\\pipeline\\model_eval.py', reloading]
[2025-05-13 17:52:42,834: INFO: _internal:  * Restarting with stat]
[2025-05-13 17:52:54,601: WARNING: _internal:  * Debugger is active!]
[2025-05-13 17:52:54,605: INFO: _internal:  * Debugger PIN: 532-605-900]
[2025-05-13 17:53:36,056: INFO: _internal:  * Detected change in 'c:\\MyDLProject\\Kidney_DL_Project\\main.py', reloading]
[2025-05-13 17:53:37,185: INFO: _internal:  * Restarting with stat]
[2025-05-13 17:53:45,916: WARNING: _internal:  * Debugger is active!]
[2025-05-13 17:53:45,919: INFO: _internal:  * Debugger PIN: 532-605-900]
